[program:conlang-server]
command = /home/joseph/.cache/pypoetry/virtualenvs/conlang-tools-kS28y4pr-py3.12/bin/conlang-server -l
directory = /home/joseph/coding_base/lang_tools/backend/conlang_tools
user = joseph
group = www-data
stdout_logfile = /var/log/conlang/stdout.log
stderr_logfile = /var/log/conlang/stderr.log
autostart = True
autorestart = True