[program:conlang-server]
command = /home/magmek/.cache/pypoetry/virtualenvs/conlang-tools-2z2gMeWR-py3.12/bin/conlang-server
directory = /var/www/lang-tools
user = magmek
group = www-data
stdout_logfile = /var/log/conlang/stdout.log
stderr_logfile = /var/log/conlang/stderr.log
autostart = True
autorestart = True